setwd("C:/Users/pc/Desktop/cancer_project")
getwd()
cancer <- read.csv("cancer.csv", header=TRUE)
head(cancer)
str(cancer)
summary(cancer)
dim(cancer)
names(cancer)
sum(is.na(cancer))
colSums(is.na(cancer))
cancer$Diagnosis <- as.factor(cancer$Diagnosis)
install.packages("caret")
install.packages("caTools")
install.packages("randomForest")
install.packages("e1071")
install.packages("ggplot2")
library(caret)
library(caTools)
library(randomForest)
library(e1071)
library(ggplot2)
set.seed(123)
split <- sample.split(cancer$Diagnosis, SplitRatio=0.7)
train <- subset(cancer, split==TRUE)
test <- subset(cancer, split==FALSE)
model <- randomForest(Diagnosis ~ ., data=train)
print(model)
pred <- predict(model, test)
confusionMatrix(pred, test$Diagnosis)
varImpPlot(model)
saveRDS(model, "Cancer_Model.rds")
model <- readRDS("Cancer_Model.rds")
write.csv(data.frame(Actual=test$Diagnosis,
                     Predicted=pred), "Predictions.csv", row.names=FALSE)                                        
